list: $/jkchr1s/staticpageblocks/models/blocktype/columns.yaml
modelClass: Jkchr1s\StaticPageBlocks\Models\BlockType
title: Static Page Block Type
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jkchr1s/staticpageblocks/blocktype/update/:id'
